// client/src/pages/Estoque.jsx
import { useState } from 'react';
import FormCard from '../components/FormCard';
import DataTable from '../components/DataTable';
import { CATEGORIAS_ESTOQUE, UNIDADES_ESTOQUE } from '../utils/constants';

const initialForm = { produto: '', categoria: 'Camiseta', quantidadeAtual: '', unidade: 'unidade', quantidadeMinima: '', observacao: '' };

export default function Estoque({ records, onSave, onUpdate, onDelete }) {
  const [form, setForm] = useState(initialForm); const [editingId, setEditingId] = useState(null); const setValue = (k, v) => setForm((p) => ({ ...p, [k]: v }));
  const baixos = records.filter((r) => Number(r.quantidadeAtual || 0) <= Number(r.quantidadeMinima || 0));
  function submit(e) { e.preventDefault(); if (!form.produto) return alert('Informe o produto/material.'); const done = editingId ? onUpdate('Estoque', editingId, form) : onSave('addEstoque', form); Promise.resolve(done).then(() => { setForm(initialForm); setEditingId(null); }); }
  return <div className="space-y-5">{baixos.length ? <div className="rounded-[2rem] bg-yellow-100 p-5 shadow-pop"><h2 className="text-xl font-black text-teepopInk">⚠️ Atenção: estoque baixo</h2><p className="mt-2 font-bold text-purple-700">{baixos.map((i) => i.produto).join(', ')}</p></div> : null}<FormCard title={editingId ? 'Editar estoque' : 'Estoque simples'} subtitle="Controle de materiais e aviso de quantidade mínima." emoji="📦"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Input label="Produto/material" value={form.produto} onChange={(v) => setValue('produto', v)} /><Select label="Categoria" value={form.categoria} onChange={(v) => setValue('categoria', v)} options={CATEGORIAS_ESTOQUE} /><Input label="Quantidade atual" type="number" value={form.quantidadeAtual} onChange={(v) => setValue('quantidadeAtual', v)} /><Select label="Unidade" value={form.unidade} onChange={(v) => setValue('unidade', v)} options={UNIDADES_ESTOQUE} /><Input label="Quantidade mínima" type="number" value={form.quantidadeMinima} onChange={(v) => setValue('quantidadeMinima', v)} /><TextArea label="Observação" value={form.observacao} onChange={(v) => setValue('observacao', v)} /><div className="md:col-span-2 flex gap-3"><button className="btn-pop bg-teepopPink text-white">{editingId ? 'Salvar edição' : 'Salvar estoque'}</button>{editingId ? <button type="button" onClick={() => { setEditingId(null); setForm(initialForm); }} className="btn-pop bg-teepopYellow text-teepopInk">Cancelar</button> : null}</div></form></FormCard><DataTable title="Histórico de estoque" records={records} columns={columns} partnerFilter={false} onEdit={(r) => { setEditingId(r.id); setForm({ ...initialForm, ...r }); window.scrollTo({ top: 0, behavior: 'smooth' }); }} onDelete={(r) => onDelete('Estoque', r.id, '')} /></div>;
}
const columns = [{ key: 'produto', label: 'Produto' }, { key: 'categoria', label: 'Categoria' }, { key: 'quantidadeAtual', label: 'Qtd atual' }, { key: 'unidade', label: 'Unidade' }, { key: 'quantidadeMinima', label: 'Qtd mínima' }, { key: 'observacao', label: 'Observação' }];
function Input({ label, value, onChange, ...props }) { return <label className="font-black text-teepopInk">{label}<input className="input-pop mt-1" value={value || ''} onChange={(e) => onChange(e.target.value)} {...props} /></label>; }
function TextArea({ label, value, onChange }) { return <label className="font-black text-teepopInk md:col-span-2">{label}<textarea className="input-pop mt-1 min-h-28" value={value || ''} onChange={(e) => onChange(e.target.value)} /></label>; }
function Select({ label, value, onChange, options }) { return <label className="font-black text-teepopInk">{label}<select className="input-pop mt-1" value={value} onChange={(e) => onChange(e.target.value)}>{options.map((o) => <option key={o} value={o}>{o}</option>)}</select></label>; }
